### ISSUE TITLE
arreglar caracteres unicode (acentos) en busquedas

### ISSUE THREAD

**Issue by azurda** [ineedblood/telegram-bot#2]

**Comment by ineedblood** [comment]
fixed  https://github.com/ineedblood/telegram-bot/commit/43a08c7197de7adefed801bfa3fecf827ffe4ad3

**Comment by azurda** [comment]
fixeddd https://github.com/ineedblood/telegram-bot/commit/43a08c7197de7adefed801bfa3fecf827ffe4ad3
